#!/bin/bash

set -e

SOURCE="$1"
DEST="$2"

cd "$1"
ORIGIN_URL=`git remote -v | grep origin | head -1 | awk '{ print $2 }'`
cd -

git clone "$SOURCE" "$DEST"

cd "$DEST"
git remote set-url origin "$ORIGIN_URL"

git pull
